<a href="https://colab.research.google.com/github/PuteraHariz/data-science-toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial 3 Data Science

Question 1

In [ ]:
import numpy as np

In [ ]:

array=np.ones((2, 2))

print(array)

[[1. 1.]
 [1. 1.]]


Question 2

In [ ]:
import numpy as np
#random floats between 0.0 and 1.0

random_array = np.random.rand(3,4)

print(random_array)


[[0.24170365 0.03829885 0.926099   0.23482145]
 [0.02855728 0.00193207 0.57537187 0.78021252]
 [0.33241878 0.6181799  0.76181147 0.62045344]]


In [ ]:
import numpy as np

# 3x4 array for a specific range of random number
random_int_array = np.random.randint(low=1, high=20, size=(3, 4))

print(random_int_array)

[[ 4 10 13  7]
 [ 3 16  9 12]
 [ 7  8 17 18]]


Question 3

In [ ]:
#With the decimal point
import numpy as np

array_one=np.ones((2, 2))

print(array_one) # Corrected: Changed '=' to '()' to call the print function

[[1. 1.]
 [1. 1.]]


In [ ]:
#With the decimal point
import numpy as np

array_one=np.zeros((2, 2))

print(array_one) # Corrected: Changed '=' to '()' to call the print function

[[0. 0.]
 [0. 0.]]


In [ ]:
#Without the decimal point
n3=np.full((2,2),1)
print(n3)

[[1 1]
 [1 1]]


In [ ]:
#Without the decimal point
n3=np.full((2,2),0)
print(n3)

[[0 0]
 [0 0]]


Question 4

In [ ]:
random_array=np.random.randint(low=35 ,high=50 ,size=(6,3))

print(random_array)

#using .T
transpose_random_array = random_array.T
print(transpose_random_array)

#using np.transpose()
transpose_random_array = np.transpose(random_array)
print(transpose_random_array)

#using .transpose()
transpose_random_array = random_array.transpose()
print(transpose_random_array)

[[49 39 46]
 [45 47 44]
 [41 44 45]
 [45 47 49]
 [35 42 45]
 [40 49 38]]
[[49 45 41 45 35 40]
 [39 47 44 47 42 49]
 [46 44 45 49 45 38]]
[[49 45 41 45 35 40]
 [39 47 44 47 42 49]
 [46 44 45 49 45 38]]
[[49 45 41 45 35 40]
 [39 47 44 47 42 49]
 [46 44 45 49 45 38]]


Question 5

In [ ]:
random_array1=np.random.randint(low=5 ,high=20 ,size=(2,2))
print(random_array1)

random_array2=np.random.randint(low=10 ,high=16 ,size=(2,2))
print(random_array2)

#dot product of two array
dot_product=np.dot(random_array1,random_array2)

print("The dot product of the two array is :")
print(dot_product)


[[12  9]
 [15 19]]
[[15 14]
 [10 11]]
The dot product of the two array is :
[[270 267]
 [415 419]]
